version: '3'
services:
  local-db:
    image: pgvector/pgvector:pg17  # or pg15, pg14 — whatever version you want
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5435:5432
    networks:
      - turborepo-network
  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    command: start --tunnel
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - WEBHOOK_URL=https://gitgrasp.hooks.n8n.cloud
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    volumes:
      - n8n_data:/volume/.n8n
    networks:
      - turborepo-network

networks:
  turborepo-network:
    external: true

volumes:
  n8n_data: